app_reclamation:
    resource: "@KarimBundle/Controller/ReclamationController.php"
    type:     annotation

app_messages:
    resource: "@KarimBundle/Controller/MessagesController.php"
    type:     annotation

ferid:
    resource: "@FeridBundle/Controller/"
    type:     annotation
    prefix:   /

raed:
    resource: "@RaedBundle/Controller/"
    type:     annotation
    prefix:   /

emna:
    resource: "@EmnaBundle/Controller/"
    type:     annotation
    prefix:   /

dorrq:
    resource: "@DorraBundle/Controller/"
    type:     annotation
    prefix:   /

sami:
    resource: "@SamiBundle/Controller/"
    type:     annotation
    prefix:   /

karim:
    resource: "@KarimBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
